version: '3.8'

networks:
  traefik-public:
    external: true
  db-private:
    driver: bridge

services:

  traefik:
    image: traefik:v3.5
    container_name: traefik
    restart: always
    command:
      - "--log.level=INFO"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      # HTTP
      - "--entrypoints.web.address=:80"

      # Redirección HTTP -> HTTPS
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"

      # HTTPS
      - "--entrypoints.websecure.address=:443"

      # Let's Encrypt
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=kam.santana@yavirac.edu.ec"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

    networks:
      - traefik-public

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer_santana
    restart: always

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainersantana.byronrm.com`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls.certresolver=myresolver"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.docker.network=traefik-public"

    networks:
      - traefik-public

  frontend:
    build: ./frontend
    container_name: frontend_santana
    restart: always

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`santana.byronrm.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik-public"

    networks:
      - traefik-public

  backend:
    build: ./backend
    container_name: backend_santana
    restart: always

    environment:
      DB_HOST: postgres_db
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: midatabase

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backsantana.byronrm.com`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.services.backend.loadbalancer.server.port=5000"
      - "traefik.docker.network=traefik-public"

    networks:
      - traefik-public
      - db-private

  postgres_db:
    image: postgres:15
    container_name: postgres_db
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: midatabase

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - db-private

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_santana
    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminpass

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgsantana.byronrm.com`)"
      - "traefik.http.routers.pgadmin.entrypoints=websecure"
      - "traefik.http.routers.pgadmin.tls.certresolver=myresolver"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik-public"

    networks:
      - traefik-public
      - db-private

volumes:
  portainer_data:
  postgres_data: